<?php
/**
 * Implements hook_element_info().
 */
function user_area_element_info() {
  $types = array(
    'area' => array(
      '#input' => TRUE,
      '#tree' => TRUE,
      '#process' => array('user_area_process'),
      '#theme' => array('user_area'),
      '#pre_render' => array('form_pre_render_conditional_form_element'),
      '#value_callback' => 'user_area_value_callback'
    )
  );
  
  return $types;
}

/**
 * element显示前对element内参数的处理
 */
function user_area_process($element, $form_state) {
    if(isset($element['default_value'])) {
        $element['#default_value'] = $element['default_value'];
    }
  return $element;
}

/**
 * element呈现的模板
 */
function theme_user_area($variables) {
  $output = '<input name="area" type="text" value=""/>';
  return $output;
}

/**
 * from submit后，element的最终值
 */
function user_area_value_callback($element, $input = FALSE, &$form_state) {
  if ($input !== FALSE) {
    // element可以由多个element组成，但只有一个返回值，其他element将不返回
    return $_POST['user_area'];
  } elseif (!empty($element['#default_value'])) {
    return $element['#default_value'];
  }
  
  return;
}

/**
 * Implements hook_theme().
 */
function user_area_theme() {
  return array(
      'user_area' => array(
        'render element' => 'element',
      )
  );
}

function user_area_menu()
{
  $items = array();
  $items['test_element'] = array(
    'title' => 'user_area',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_area_form'),
    'access callback' => TRUE,
    'expanded' => TRUE,
  );
  return $items;
}

function user_area_form($form, &$form_state) {
    $form = array();
    $form['user_area'] = array(
      '#type' => 'user_area',
      '#title' => 'user_area',
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Submit'
    );
    return $form;
}

function user_area_form_submit($form, &$form_state) {
    drupal_set_message('value: '.$form_state['values']['user_area']);
}